//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealCompanyNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DealsCopmanyEntities : DbContext
    {
        public DealsCopmanyEntities()
            : base("name=DealsCopmanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClaimedDeal> ClaimedDeals { get; set; }
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<DealCompanyNew.Models.InformationVM> InformationVMs { get; set; }
    }
}
